# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Bootstrap Download Links and Destinations (Bootstrap v4.5.3, JQuery v3.5.1)
# jquery-3.5.1.min.js -> https://code.jquery.com/jquery-3.5.1.min.js
# jquery-3.5.1.min.map -> https://code.jquery.com/jquery-3.5.1.min.map
# scss/* -> dependencies/css/bootstrap/ & dist/js/*.bundle -> dependencies/js/bootstrap/ -> https://github.com/twbs/bootstrap/archive/v4.5.3.zip

# Site settings
title: CGVLab
email: null@cs.purdue.edu
description: > # This means 'ignore newlines until "baseurl:"'
  The website of the Computer Graphics and Visualization Laboratory (CGVLab) at Purdue University.
baseurl: ""
url: ""

include:
  - .htaccess
  - _pages

sass:
  sass_dir: /dependencies/css

# Data directories and files
dir_theme_css: /theme/css
dir_theme_js: /theme/js
dir_theme_images: /theme/images

dir_resources_files: /resources/files
dir_resources_images: /resources/images
dir_resources_videos: /resources/videos
dir_resources_papers: /resources/papers

dir_dependencies_css: /dependencies/css
dir_dependencies_js: /dependencies/js

file_theme_jquery_js: jquery-3.5.1.min.js
file_theme_bootstrap_js: bootstrap.bundle.min.js

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # Default for kramdown is false. This will enable using Markdown links

plugins:
  - jekyll-scholar

scholar:
  bibliography_list_tag: ul
