# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Bootstrap Download Links and Destinations (Bootstrap v4.5.3, JQuery v3.5.1)
# jquery-3.5.1.min.js from https://code.jquery.com/jquery-3.5.1.min.js
# jquery-3.5.1.min.map from https://code.jquery.com/jquery-3.5.1.min.map
# scss/* -> dependencies/css/bootstrap/ & dist/js/*.bundle -> dependencies/js/bootstrap/ from https://github.com/twbs/bootstrap/archive/v4.5.3.zip

# All custom (CGVLab-specific) content is located in the "resources", "theme", "_pages", "_bibliography", and "_data" folders.
# Other files that are CGVLab-specific are "_config.yml", "README.md", "LICENSE", and "favicon.ico".
# The only exception to these rules are the files located in the "_includes/_publication" and "_includes/_person" folders.

# Site settings (SEO)
title: CGVLab
description: Computer Graphics and Visualization Laboratory at Purdue University
url: "https://cgvlab.purdue.edu"
parent_organization: Department of Computer Science at Purdue University
parent_organization_url: "https://cs.purdue.edu"
logo: /theme/images/icon.png
locale: en_US
baseurl: ""

# Site defaults
defaults:
  - scope:
      path: ""
    values:
      image: /theme/images/icon.png

# Include files in conversion
include:
  - .htaccess
  - _pages

# SASS theme
sass:
  sass_dir: /dependencies/css

# Data directories and files
dir_theme_css: /theme/css
dir_theme_js: /theme/js
dir_theme_images: /theme/images

dir_resources_files: /resources/files
dir_resources_images: /resources/images
dir_resources_videos: /resources/videos
dir_resources_publications: /resources/papers

dir_dependencies_css: /dependencies/css
dir_dependencies_js: /dependencies/js

file_theme_jquery_js: jquery-3.5.1.min.js
file_theme_bootstrap_js: bootstrap.bundle.min.js

# Settings
enable_lazy_loading: true

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: '\n\n'
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: false # Default for kramdown is false. This will enable using Markdown links

# Plugins
plugins:
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-analytics
  - jekyll-seo-tag

# Settings for jekyll-scholar
scholar:
  bibliography_list_tag: ul

# Settings for jekyll-analytics
jekyll_analytics:
  GoogleAnalytics:
    id: UA-82472331-1
    anonymizeIp: false
